services:
  mysql_users:
    container_name: "users_database"
    image: mysql:8.0.23
    networks: 
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "users"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    command: --default-authentication-plugin=mysql_native_password
  users-service:
      container_name: "users-service"
      build:
        context: ./../users-service
        dockerfile: ./users-service.dockerfile
      restart: always
      ports:
        - "8081:8081"
      deploy:
        mode: replicated
        replicas: 1